-- MySQL Script generated by MySQL Workbench
-- Mon May  6 21:39:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RoadsAndPotholes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RoadsAndPotholes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RoadsAndPotholes` DEFAULT CHARACTER SET utf8 ;
USE `RoadsAndPotholes` ;

-- -----------------------------------------------------
-- Table `RoadsAndPotholes`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoadsAndPotholes`.`branch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `house_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoadsAndPotholes`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoadsAndPotholes`.`worker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `gender` ENUM('M', 'W') NULL,
  `job_title` VARCHAR(45) NULL,
  `birthdate` DATE NOT NULL,
  `hire_date` DATE NOT NULL,
  `comment` VARCHAR(200) NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`id`, `branch_id`),
  INDEX `fk_worker_branch_idx` (`branch_id` ASC),
CONSTRAINT `fk_worker_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `RoadsAndPotholes`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
